### ISSUE TITLE
rat race

### ISSUE THREAD

**Issue by wheresrhys** [hunterloftis/awaiting#13]
Any interest in adding this into your library. It's like race, but ignores errors unless all promises error
https://github.com/Financial-Times/promise-rat-race

**Comment by hunterloftis** [comment]
That's interesting, can you outline a use case for me?

**Comment by wheresrhys** [comment]
It's been useful when using microservices, in particular racing responses
from different nodes for reliability and performance. For one service we
have a cached response in the cdn, which has very flat response times, but
the median is far slower than hitting the origin directly, although the
origin sometimes experiences severe spikes in latency. Racing the two gives
far more reliable response times

**Comment by hunterloftis** [comment]
Gotcha - in that case, you can use this already:

- https://hunterloftis.github.io/awaiting/#single

```js
const winner = a.single([ rat0, rat1, rat2, rat3 ], Infinity)
```

The 2nd argument is the number of errors to ignore.

**Comment by wheresrhys** [comment]
I had a feeling something in the library would already cover it.  thanks
