### ISSUE TITLE
release in CDN?

### ISSUE THREAD

**Issue by Cologler** [hunterloftis/awaiting#17]
Does any CDN contains this library?

**Comment by MartinKolarik** [comment]
You can use https://www.jsdelivr.com/package/npm/awaiting

**Comment by Cologler** [comment]
Thanks.

**Comment by MartinKolarik** [comment]
Consider sending a PR to add the link to docs so that others can find it too.

**Comment by Cologler** [comment]
@MartinKolarik like #20 ?
