### ISSUE TITLE
FYI: type definitions submitted to flow-typed

### ISSUE THREAD

**Issue by hallettj** [hunterloftis/awaiting#6]
Hi! I'm the one who made a comment on Reddit about submitting type definitions. The pull request is in: https://github.com/flowtype/flow-typed/pull/774

You mentioned that you might want to incorporate type annotations in the source code. The definitions here could be pulled into your own code if you want to do that. I actually prefer to ship type definitions with the library itself when writing my own libraries, and I have a [Makefile](https://gist.github.com/hallettj/29b8e7815b264c88a0a0ee9dcddb6210) that I use in most of my projects for that purpose. The way that works is that you put type annotations in your source code in `src/whatever.js`, the build process uses Babel to strip out annotations when building `lib/whatever.js`, and the build process also puts a copy of the original source with annotations preserved in `lib/whatever.js.flow`. Flow will automatically look for type definitions for any `*.js` file in a file called `*.js.flow`.

There are advantages to shipping types yourself, and to publishing types through flow-typed. The main advantage of flow-typed is that it can publish variations of your types for multiple versions of Flow. That can be useful for consumers who are stuck on an older version of Flow. On the other hand if types are bundled in your library you can incorporate type-checking into your tests, you can be assured that type definitions stay in sync with library releases, and you have control over publication. (The last PR that I submitted to flow-typed has been waiting to be merged for about a month.)

**Comment by hunterloftis** [comment]
Thanks for both the PR and the explanation of tradeoffs!
